### ISSUE TITLE
Docker image usage

### ISSUE THREAD

**Issue by laurivosandi** [suprememoocow/victron-exporter#35]
Please add into README how to use the Docker image. I tried to run `ghcr.io/suprememoocow/victron-exporter:v0.5.0-amd64` but it says `exec /usr/local/bin/victron-exporter: no such file or directory`. Oddly enough the binary seems to be inside the image  and entrypoint seems to invoke the right path

**Comment by irrwitzer42** [comment]
Hi,

Thank you @suprememoocow for your work and this exporter!

Just as a reference for others looking for an answer to this question, I found a ready to use docker image based on this code here:

theempty/victron-exporter: [theempty/victron-exporter](https://github.com/TheEmpty/victron-exporter-dockerfile)
                                             Thanks @theempty for your part in this and the complete Dockerfile  as well ;-) 

I used it in my docker-compose.yml like this:

```
  victron-exporter:
    image: theempty/victron-exporter:latest
    container_name: victron-exporter
    restart: unless-stopped
    expose:
      - 9226
    command:
      - '-mqtt.host'
      - '192.168.1.13'
      - '-web.listen-address'
      - '0.0.0.0:9226'
```
